### PR TITLE
Solved issue #5 smooth scrolling

### PR DESCRIPTION
**Pull request by bansal-harsh-2504**
Added smooth scrolling for nav-links

### CODE REVIEW

**Comment by Ketanop321** [comment]
Did you ran this project on your local computer??

**Comment by bansal-harsh-2504** [comment]
> Did you ran this project on your local computer??

Yes, this is an empty repo

**Comment by Ketanop321** [comment]
> > Did you ran this project on your local computer??
> 
> Yes, this is an empty repo

how did you solve my issue?

**Comment by bansal-harsh-2504** [comment]
> > > Did you ran this project on your local computer??
> > 
> > 
> > Yes, this is an empty repo
> 
> so,you are merging a pr to empty repo

Yes

**Pull request closed without merging**
